INCORRECT_CREDENTIALS = "incorrect_username_or_password"
INVALID_HOST = "invalid_host"
NO_STUDENTS_ACCOUNT = "no_students_account"
AUTHENTICATION_REQUIRED = "authentication_required"
UNKNOWN_ERROR = "unknown_error"