    name: Backend Penetration Unit-Tests 2.0
    on: [push]
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Set up Python 3.10.4
          uses: actions/setup-python@v2
          with:
            python-version: 3.10.4
        - name: psycopg2 prerequisites
          run: sudo apt-get install python-dev libpq-dev
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r .github/workflows/requirements.txt
        - name: Run penetration tests
          working-directory: tests
          run: pytest test.py -vs
