    name: Backend
    on: [push]
    env:
      PYTEST_ADDOPTS: "--color=yes"
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3
          with:
            path: ./wulkanowy-web/
            submodules: true
        - name: Set up Python 3.11.1
          uses: actions/setup-python@v4
          with:
            python-version: 3.11.1
        - name: psycopg2 prerequisites
          run: sudo apt-get install python3-capstone libpq-dev
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r ./wulkanowy-web/.github/workflows/requirements.txt
        - name: Run tests
          working-directory: ./wulkanowy-web/backend/tests
          run: pytest test.py
