    name: Backend
    on: [push]
    env:
      PYTEST_ADDOPTS: "--color=yes"
    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Set up Python 3.10.4
          uses: actions/setup-python@v3
          with:
            python-version: 3.10.4
        - name: psycopg2 prerequisites
          run: sudo apt-get install python-dev libpq-dev git
        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r .github/workflows/requirements.txt
        - name: Run tests
          working-directory: /home/runner/work/wulkanowy-web/wulkanowy-web/
          run: pytest /home/runner/work/wulkanowy-web/wulkanowy-web/backend/test.py
