name: Wulkanowy-Web Deployer 2.0
on:
  push:
    branches: [ deploy ]
  workflow_dispatch:
jobs:
  frontendt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ./wulkanowy-web/
      - name: Install deps
        working-directory: ./frontend
        run: npm install --immutable
      - name: Build app
        working-directory: ./frontend
        run: npm run build

  backendt:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          path: ./wulkanowy-web/
      - name: Set up Python 3.10.5
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.5
      - name: psycopg2 prerequisites
        run: sudo apt-get install python-dev libpq-dev
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./wulkanowy-web/.github/workflows/requirements.txt
      - name: Run tests
        working-directory: ./wulkanowy-web/backend/tests
        run: pytest test.py
  build:
    runs-on: ubuntu-latest
    needs:
      - backendt
      - frontendt
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          path: ./wulkanowy-web/
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with: 
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: 'Error'
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
      - name: Stop the Wulkanowy-Web Frontend server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl stop wulkanowywebf'
      - name: Stop the Wulkanowy-Web Backend server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl stop wulkanowywebb'
      - name: Deploy using rsync
        run: rsync -avz /home/runner/work/wulkanowy-web/wulkanowy-web/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/Documents/Server-Wulkanowy-Web/wulkanowy-web/
      - name: Start the Wulkanowy-Web Backend server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl start wulkanowywebb'
      - name: Start the Wulkanowy-Web Frontend server
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl start wulkanowywebf'
      - name: Sleep for 20 seconds
        run: sleep 20s
      - name: Check Wulkanowy-Web Frontend server errors
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl status wulkanowywebf'
      - name: Check Wulkanowy-Web Backend server errors
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo systemctl status wulkanowywebb'
      - name: Collect Logs from Wulkanowy-Web Backend server
        if: ${{ failure() }}
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo journalctl -xe --since "30 seconds ago" | grep start-web-backend.sh'
      - name: Collect Logs from Wulkanowy-Web Frontend server
        if: ${{ failure() }}
        run: ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} 'sudo journalctl -xe --since "30 seconds ago" | grep start-web-frontend.sh'
