    name: Frontend
    on: [push]
    jobs:
      build:
        runs-on: ubuntu-latest
        
        steps:
        - uses: actions/checkout@v1
        - name: Install npm
          run: npm install --prefix frontend
        - name: Build app
          run: npm run dev --prefix frontend
