    name: Frontend
    on: [push]
    jobs:
      build:

        runs-on: ubuntu-latest
        
        steps:
        - name: Check out code
          uses: actions/checkout@v2
        - name: Install deps
          working-directory: ./frontend
          run: npm install --immutable
        - name: Build app
          working-directory: ./frontend
          run: npm run build