INCORRECT_CREDENTIALS = "incorrect_username_or_password"
INVALID_HOST = "invalid_host"
NO_SYMBOLS = "no_students_account"
AUTHENTICATION_REQUIRED = "authentication_required"
UNKNOW_ERROR = "unknow_error"